AdaptiveTravelPlanner/urls.py
from django.contrib import admin
from django.urls import path, include
from Zomato.views import simplePageZomato
from PastTravels.views import pagesIndex, pastTravels
from survey.views import showSurvey, surveySubmitted
from django.contrib.auth.views import LoginView, LogoutView
from userProfile.views import ProfileDetailView, HomeView, RegisterView
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('index/', pagesIndex, name='index'),
    path('admin/', admin.site.urls),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', HomeView.as_view(), name='home'),
    path('survey/', showSurvey, name='survey'),
    path('survey_submit/', surveySubmitted),

    # Past Travels
    path('pastTravels/', include('PastTravels.urls')),
    path('recommendation/', include('Recommendation.urls')),

    path('view_model', include('UserModel.urls')),

    path('simplepageZomato/faf', simplePageZomato),
    path('profile/', login_required(ProfileDetailView.as_view()),
         name='profile')
]

UserModel/urls.py
from django.urls import path
from .views import model_view


urlpatterns = [
    path('', model_view, name="view_model"),
]

userProfile/urls.py
from django.urls import re_path

from .views import ProfileDetailView
app_name = 'profiles'

urlpatterns = [
    re_path(r'^(?P<username>[\w-]+)/$', ProfileDetailView.as_view(), name='detail'),
    re_path(r'profiles/user$',ProfileDetailView.as_view(), name ='profile')
]

userProfile/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.models import User
from django.urls import reverse
from django.views.generic import CreateView, DetailView, View
from survey.views import showSurvey
from django.db.models import Count
import datetime

from UserModel.models import FirstLogin


class RegisterView(SuccessMessageMixin, CreateView):
    form_class = UserCreationForm
    template_name = 'registration/register.html'
    success_url = '/login'
    success_message = "Your account was created successfully."

    def dispatch(self, *args, **kwargs):
        return super(RegisterView, self).dispatch(*args, **kwargs)


class ProfileDetailView(DetailView):
    template_name = 'profile/user.html'

    def get_object(self):
        user = self.request.user
        return user



class HomeView(DetailView):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            firstlogin_obj, _ = FirstLogin.objects.get_or_create(
                user=request.user, defaults=dict(first_login=True))
            if firstlogin_obj.first_login:
                return showSurvey(request)

        # in all other cases
        return HttpResponseRedirect(reverse('recommendation_search'))

userProfile/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang=en>

<head>
    <title>{% block head_title %}Mulberry.com{% endblock head_title %}</title>
      {% include 'snippets/css.html' %}
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" >
      <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/solid.js" integrity="sha384-+Ga2s7YBbhOD6nie0DzrZpJes+b2K1xkpKxTFFcx59QmVPaSA8c7pycsNaFwUK6l" crossorigin="anonymous"></script>
      <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/fontawesome.js" integrity="sha384-7ox8Q2yzO/uWircfojVuCQOZl+ZZBg2D2J5nkpLqzH1HY0C1dHlTKIbpRz/LG23c" crossorigin="anonymous"></script>
   <style>

        body {
         background: url('{% static "background-image.jpg" %}') no-repeat center center fixed;
         -webkit-background-size: cover;
         -moz-background-size: cover;
         -o-background-size: cover;
         background-size: cover;
        }
   </style>

    {% block extra_head %}{% endblock %}
</head>
<body>
{% include 'snippets/nav.html' %}
{% if messages %}
    <div class="alert messages text-center">
        {% for message in messages %}
            <b>{{ message }}</b><br/>
        {% endfor %}

    </div>
{% endif %}

<div class='container'>
    {% block content %}{% endblock content %}
</div>

<footer>
    <p></p><p></p>
{#    <p align="center"><a href='{% url "index" %}' >DEV: index of pages</a></p>#}
</footer>
{#{% include 'snippets/js.html' %}#}
</body>
</html>

userProfile/templates/home.html
{% extends "base.html" %}

{% block content %}
{% if not request.user.is_authenticated %}
    <div class='row'>
    <div class='col-sm-6 col-sm-offset-3 text-center'>
    <p class='lead'>
    This is the home page of the Travel Planner.<br/>

    <a href='{% url "register" %}'>Join us</a>
    </p>
    <hr/>
    </div>

    </div>
{% else %}
<div class='row'>
<div class='col-sm-6 col-sm-offset-3'>
<h3>Adaptive Recommendations:</h3>
{% for obj in object_list %}


        <div class='thumbnail'>
            <h3><a href='{% url "profiles:detail" username=obj.user.username %}'>{{ obj.user.username }}</a></h3>
            <h4>{{ obj.name }}</h4>
            <b>{{ obj.name }}:</b> with
             {% for ing in obj.get_contents %}
                <a href='{% url "profiles:detail" username=obj.user.username %}?q={{ ing}}'>{{ ing}}</a>
            {% endfor %}
            </p>
        </div>


{% endfor %}

</div>
</div>
{% endif %}
{% endblock content %}